name: delve
version: '0.0.0'
synopsis: CLI File Browser
description: CLI File Browser
category: Utility
author: Chris Penner
maintainer: christopher.penner@gmail.com
copyright: 2019 Chris Penner
license: BSD3
github: ChrisPenner/delve.git
tested-with: GHC==8.4.4
ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Widentities
- -Wredundant-constraints
- -fhide-source-paths
- -Wmissing-export-lists
- -Wpartial-fields
dependencies:
- base >=4.11.1.0
- brick == 0.46
- vty
- mtl
- directory-tree
- recursion-schemes
- free
- comonad
- vector
- containers
- directory
- filepath
- unix
- lens
- brick-filetree
- async
- streaming
- generic-lens
- text
- unliftio


library:
  source-dirs: src

default-extensions:
  - DeriveGeneric
  - TypeApplications

executables:
  delve:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
      - delve
      - brick
      - vty


tests:
  delve-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delve

